[custom.all.parser]
type = "local"
path = "."
ipkg = "parser.ipkg"
test = "test/test.ipkg"

[custom.all.parser-docs]
type = "local"
path = "docs"
ipkg = "docs.ipkg"

[custom.all.parser-test]
type = "local"
path = "test"
ipkg = "test.ipkg"

[custom.all.parser-profile]
type = "local"
path = "profile"
ipkg = "profile.ipkg"

[custom.all.pretty-show]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-pretty-show"
commit = "latest:main"
ipkg   = "pretty-show.ipkg"

[custom.all.hedgehog]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-hedgehog"
commit = "latest:main"
ipkg   = "hedgehog.ipkg"
