[custom.all.parser]
type = "local"
path = "."
ipkg = "parser.ipkg"
test = "test/test.ipkg"

[custom.all.parser-docs]
type = "local"
path = "docs"
ipkg = "docs.ipkg"

[custom.all.parser-test]
type = "local"
path = "test"
ipkg = "test.ipkg"

[custom.all.parser-profile]
type = "local"
path = "profile"
ipkg = "profile.ipkg"

[custom.all.parser-toml]
type = "local"
path = "toml"
ipkg = "parser-toml.ipkg"
test = "test/test.ipkg"

[custom.all.parser-toml-test]
type = "local"
path = "toml/test"
ipkg = "test.ipkg"

[custom.all.parser-json]
type = "local"
path = "json"
ipkg = "parser-json.ipkg"
test = "test/test.ipkg"

[custom.all.parser-json-test]
type = "local"
path = "json/test"
ipkg = "test.ipkg"

[custom.all.parser-webidl]
type = "local"
path = "webidl"
ipkg = "parser-webidl.ipkg"
test = "test/test.ipkg"

[custom.all.parser-webidl-test]
type = "local"
path = "webidl/test"
ipkg = "test.ipkg"

[custom.all.elab-util]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-elab-util"
commit = "latest:main"
ipkg   = "elab-util.ipkg"

[custom.all.sop]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-sop"
commit = "latest:main"
ipkg   = "sop.ipkg"

[custom.all.elab-pretty]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-elab-util"
commit = "latest:main"
ipkg   = "elab-pretty.ipkg"

[custom.all.pretty-show]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-pretty-show"
commit = "latest:main"
ipkg   = "pretty-show.ipkg"

[custom.all.json]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-json"
commit = "latest:main"
ipkg   = "json.ipkg"

[custom.all.hedgehog]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-hedgehog"
commit = "latest:main"
ipkg   = "hedgehog.ipkg"

[custom.all.refined]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-refined"
commit = "latest:main"
ipkg   = "refined.ipkg"

[custom.all.algebra]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-algebra"
commit = "latest:main"
ipkg   = "algebra.ipkg"
