[custom.all.parser]
type = "local"
path = "."
ipkg = "parser.ipkg"
test = "test/test.ipkg"

[custom.all.parser-test]
type = "local"
path = "test"
ipkg = "test.ipkg"

[custom.all.parser-profile]
type = "local"
path = "profile"
ipkg = "profile.ipkg"

[custom.all.pretty-show]
type = "local"
path = "../pretty-show"
ipkg = "pretty-show.ipkg"

[custom.all.hedgehog]
type = "local"
path = "../hedgehog"
ipkg = "hedgehog.ipkg"
