---
name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build ${{ github.repository }} with Idris2 latest
    runs-on: ubuntu-latest
    env:
      PACK_DIR: /root/.pack
    strategy:
      fail-fast: false
    container: ghcr.io/stefan-hoeck/idris2-pack:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build parser
        run: pack install parser
      - name: Test parser
        run: pack test parser -n 1000
      - name: Build parser-toml
        run: pack install parser-toml
      - name: Test parser-toml
        run: pack test parser-toml -n 1000
      - name: Typecheck docs
        run: pack typecheck parser-docs
